
export default function Terms() {
  return (
    <>
      <div className="legal-page">
        <h2>Terms of Service</h2>
        <p className="legal-updated">Last updated: April 2026</p>

        <p>
          By using Flipt (&ldquo;the Service&rdquo;), you agree to these Terms of Service. If you do not agree, please do not use the Service.
        </p>

        <h3>1. Description of Service</h3>
        <p>
          Flipt is an AI-powered resale assistant that helps users identify items, estimate resale values,
          compare prices across platforms, and generate listing descriptions. The Service is provided &ldquo;as is&rdquo;
          and is intended to assist with — not replace — your own judgment when buying and selling items.
        </p>

        <h3>2. Free Tier and Subscriptions</h3>
        <p>
          Flipt offers a free tier that includes 5 scans per month. Additional scans can be earned through our referral program (3 bonus scans per referral).
        </p>
        <p>
          <strong>Flipt Pro</strong> ($4.99/month) provides unlimited scans, priority AI analysis, listing history, and multi-photo support.
          Subscriptions renew automatically each month. You may cancel at any time; cancellation takes effect at the end of the current billing period.
          No refunds are provided for partial months.
        </p>

        <h3>3. AI Accuracy Disclaimer</h3>
        <p>
          <strong>Flipt provides price estimates and market data generated by artificial intelligence. These are estimates only and should not be relied upon as guaranteed valuations.</strong>
        </p>
        <p>
          AI-generated price estimates are based on the model&apos;s training data and may not reflect real-time market conditions.
          Actual sale prices depend on many factors including item condition, local demand, listing quality, negotiation, and market fluctuations.
          We strongly recommend that users verify prices independently on their chosen selling platform before making listing or purchasing decisions.
        </p>
        <p>
          Flipt does not guarantee the accuracy of any valuation, brand identification, authenticity assessment, damage analysis,
          or market trend data provided through the Service.
        </p>

        <h3>4. Prohibited Uses</h3>
        <p>You agree not to use Flipt to:</p>
        <ul>
          <li>Scan, list, or sell stolen property</li>
          <li>Create fraudulent or misleading listings</li>
          <li>Sell counterfeit, replica, or inauthentic items represented as genuine</li>
          <li>Violate any applicable local, provincial, or federal laws</li>
          <li>Harass, abuse, or harm other users of the Flipt marketplace or community features</li>
          <li>Attempt to reverse-engineer, scrape, or abuse the AI scanning system</li>
        </ul>
        <p>
          Violation of these terms may result in immediate suspension or termination of your account and access to the Service.
        </p>

        <h3>5. Intellectual Property</h3>
        <p>
          The Flipt name, logo, design system, and underlying technology are the property of Flipt and are protected by intellectual property laws.
          Listing descriptions and titles generated by the AI are provided for your use and may be freely used on any selling platform.
          You retain all rights to your own photos and content.
        </p>

        <h3>6. User Content</h3>
        <p>
          By posting content to the Flipt marketplace or community feed, you grant Flipt a non-exclusive, royalty-free license to display
          that content within the Service. You represent that you have the right to share any content you post
          and that it does not infringe on any third party&apos;s rights.
        </p>

        <h3>7. Limitation of Liability</h3>
        <p>
          To the maximum extent permitted by law, Flipt and its operators shall not be liable for any indirect, incidental,
          special, consequential, or punitive damages arising from your use of the Service. This includes but is not limited to:
          losses from inaccurate price estimates, failed sales, items listed at incorrect prices, or reliance on AI-generated data.
        </p>
        <p>
          Our total liability to you for any claims arising from the Service shall not exceed the amount you have paid to Flipt
          in the twelve months preceding the claim, or $50 CAD, whichever is greater.
        </p>

        <h3>8. Indemnification</h3>
        <p>
          You agree to indemnify and hold harmless Flipt from any claims, damages, or expenses arising from your use of the Service,
          your violation of these Terms, or your violation of any third party&apos;s rights.
        </p>

        <h3>9. Governing Law</h3>
        <p>
          These Terms are governed by and construed in accordance with the laws of the Province of Ontario, Canada,
          without regard to its conflict of law provisions. Any disputes arising from these Terms or the Service
          shall be resolved in the courts of Ontario, Canada.
        </p>

        <h3>10. Changes to Terms</h3>
        <p>
          We reserve the right to modify these Terms at any time. When we make material changes,
          we will provide notice through the Service. Your continued use of Flipt after such changes
          constitutes your acceptance of the revised Terms.
        </p>

        <h3>11. Termination</h3>
        <p>
          We may suspend or terminate your access to the Service at any time for violation of these Terms or for any other reason
          at our sole discretion. Upon termination, your right to use the Service ceases immediately.
          Data stored locally on your device will remain until you clear it.
        </p>

        <h3>Contact</h3>
        <p>
          For questions about these Terms of Service, contact us at{" "}
          <a href="mailto:legal@flipt.app">legal@flipt.app</a>.
        </p>
      </div>
    </>
  )
}
